### ISSUE TITLE
It makes P2WSH not right.

### ISSUE THREAD

**Issue by Andy19999999999999** [mcdallas/cryptotools#14]
from cryptotools.BTC import generate_keypair, pubkey_to_address, push, script_to_address, OP

private, public = generate_keypair()
print(private.hex())
print(private.wif())
print(private.wif(compressed=True))

script = push(public.encode(compressed=True)) + OP.CHECKSIG.byte
print(public.hex())
print(public.hex(compressed=True))
print(pubkey_to_address(public, 'P2PKH'))
print(public.to_address('P2PKH', compressed=True))
print(public.to_address('P2WPKH'))
print(script_to_address(script, 'P2WSH'))
print(script_to_address(script, 'P2WSH-P2SH'))
print(script_to_address(script, 'P2SH'))
![Снимок экрана (15)](https://user-images.githubusercontent.com/82683809/119803239-f14cd800-bee7-11eb-9ca3-07b372383f80.png)

**Comment by Andy19999999999999** [comment]
But the right one is correct not cryptotools.

**Comment by mcdallas** [comment]
If you use the same script you'll get the same result

**Comment by mcdallas** [comment]
I am trying to explain to you that this line of your code is wrong:
> script = push(public.encode(compressed=True)) + OP.CHECKSIG.byte

**Comment by Andy19999999999999** [comment]
Excuse me, maybe I don't understand something. This line from your sample "Create keys/addresses (including segwit)":
# Simple <key> <OP_CHECKSIG> script
>>> script = push(public.encode(compressed=True)) + OP.CHECKSIG.byte
>>> script_to_address(script, 'P2WSH')
'bc1q8yh8l8ft3220q328hlapqhflpzy6xvkq6u36mctk8gq5pyxm3rwqv5h5dg'

**Comment by mcdallas** [comment]
Yes that's a nonsense script I made up as an example, no one generates addresses with that script it's just for demonstration purposes. You need to substitute your own script.

**Comment by Andy19999999999999** [comment]
Thank you I see.
