### ISSUE TITLE
How to install offline?

### ISSUE THREAD

**Issue by lzunsec** [mcdallas/cryptotools#16]
Simply doing `sudo python3 setup.py install` on my raspberry pi zero which has no internet access dit not work, I get

```
python3
from cryptotools import Xprv
cannot import name 'Xprv' from cryptotools
```

`/usr/local/lib/python3.7/dist-packages/cryptotools-0.1-py3.7.egg` exists but there should exist a folder here, not a .egg I guess.

Thanks

**Comment by mcdallas** [comment]
The following seems to work for me
* Click Code --> Download zip
* Move the `cryptotools-master.zip` to the airgapped machine i.e put it in /tmp
* `cd /tmp`, `unzip cryptotools-master.zip`
*  `cd cryptotools-master`, `python3 setup.py install`
*  `python3`, `from cryptotools import Xprv`
