### ISSUE TITLE
How to change to testnet?

### ISSUE THREAD

**Issue by lightlizm** [mcdallas/cryptotools#2]
Hi， I want to change to testnet ,and then create a address in testnet . What can I do it?
Thanks

**Comment by mcdallas** [comment]
@lightlizm change the environmental variable CRYPTOTOOLS_NETWORK to 'test' prior to importing the library

**Comment by reiven** [comment]
As a suggestion, it will be great to add to the README more clearly. I was able to infer it from reading the samples but it can be useful to add a section for this. I can send a PR for this if you want
