### ISSUE TITLE
Problems installing cryptotools with pip

### ISSUE THREAD

**Issue by Anynomouss** [mcdallas/cryptotools#22]
HI mcdallas,

Thx to your awesome library I have now a security proof script up and running, that verifies extra signatures by replacing the ones in the Witness data.
Unfortunately, it only works on one computer, the other one gives errors when installing the library.
Also others in the Grin Council who I asked to check have similar issues. I will post the errors here below, do you have any idea what the issue might be and how to solve it?:

 pip install git+https://github.com/mcdallas/cryptotools.git@master
Downloading/unpacking git+https://github.com/mcdallas/cryptotools.git@master
  Cloning https://github.com/mcdallas/cryptotools.git (to master) to /var/folders/mr/5qs09f_56xjgy576pm_bzm1w0000gn/T/pip-Yy0873-build
  Running setup.py (path:/var/folders/mr/5qs09f_56xjgy576pm_bzm1w0000gn/T/pip-Yy0873-build/setup.py) egg_info for package from git+https://github.com/mcdallas/cryptotools.git@master
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/var/folders/mr/5qs09f_56xjgy576pm_bzm1w0000gn/T/pip-Yy0873-build/setup.py", line 5, in <module>
        from cryptotools import __doc__ as docstring
      File "cryptotools/__init__.py", line 7, in <module>
        from .BTC import *
      File "cryptotools/BTC/__init__.py", line 1, in <module>
        from cryptotools.ECDSA.secp256k1 import (
      File "cryptotools/ECDSA/__init__.py", line 8
        assert self in curve, f"Point {x}, {y} not in curve"
                                                           ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/var/folders/mr/5qs09f_56xjgy576pm_bzm1w0000gn/T/pip-Yy0873-build/setup.py", line 5, in <module>

    from cryptotools import __doc__ as docstring

  File "cryptotools/__init__.py", line 7, in <module>

    from .BTC import *

  File "cryptotools/BTC/__init__.py", line 1, in <module>

    from cryptotools.ECDSA.secp256k1 import (

  File "cryptotools/ECDSA/__init__.py", line 8

    assert self in curve, f"Point {x}, {y} not in curve"

                                                       ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /var/folders/mr/5qs09f_56xjgy576pm_bzm1w0000gn/T/pip-Yy0873-build
Storing debug log for failure in /Users/tromp/Library/Logs/pip.log
$ python --version
Python 2.7.16
$ pip --version
pip 1.5.2 from /Library/Python/2.7/site-packages/pip-1.5.2-py2.7.egg (python 2.7)_

**Comment by Anynomouss** [comment]
Woops, turns out I accidentally provide them with the wrong installation command

`pip install git+https://github.com/mcdallas/cryptotools.git@master`

instead of:

`pip install git+https://github.com/mcdallas/cryptotools.git@master#egg=cryptotools`

**Comment by mcdallas** [comment]
Yes only python 3.6+ is supported which added the secrets module and a bunch of other stuff
