### ISSUE TITLE
incomplete test instructions?!

### ISSUE THREAD

**Issue by tromp** [mcdallas/cryptotools#23]
Following the testing suggestions gives:

$ python -m unittest

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

**Comment by mcdallas** [comment]
Hey @tromp , can't reproduce, does this not work?

![image](https://user-images.githubusercontent.com/15388116/131246589-02e7b9be-3050-4424-9823-9b4fbd728cb3.jpeg)

**Comment by tromp** [comment]
Oh, I had done
  pip install git+https://github.com/mcdallas/cryptotools.git@master#egg=cryptotools
(after some failed variations) and then got lost in this jungle of directories:

/private/var/folders/mr/5qs09f_56xjgy576pm_bzm1w0000gn/T/pip-B4GY8t-build
/private/var/folders/mr/5qs09f_56xjgy576pm_bzm1w0000gn/T/pip-B4GY8t-build
/private/var/folders/mr/5qs09f_56xjgy576pm_bzm1w0000gn/T/pip-Yy0873-build
/private/var/folders/mr/5qs09f_56xjgy576pm_bzm1w0000gn/T/pip-Yy0873-build
/private/var/folders/mr/5qs09f_56xjgy576pm_bzm1w0000gn/T/pip-q9J7_7-build
/private/var/folders/mr/5qs09f_56xjgy576pm_bzm1w0000gn/T/pip-q9J7_7-build
/private/var/folders/mr/5qs09f_56xjgy576pm_bzm1w0000gn/T/pip_build_tromp
/private/var/folders/mr/5qs09f_56xjgy576pm_bzm1w0000gn/T/pip_build_tromp

Now that I do a straight clone, it works:-)
