### ISSUE TITLE
multisig logic appears faulty

### ISSUE THREAD

**Issue by tromp** [mcdallas/cryptotools#24]
The code at https://github.com/mcdallas/cryptotools/blob/master/cryptotools/BTC/script.py#L392-L404
only checks that each provided signature is valid for some pubkey, but doesn't check how many different pubkeys are signed for. It thus allows you to sign m times for the same pubkey, which is 1/k, not m/k.

**Comment by tromp** [comment]
A simple solution is to remove pub from keys after line 399. That prevents a public key from being signed for more than once.

**Comment by mcdallas** [comment]
Good catch! Should definitely check for unique public keys, I’ll add a test

**Comment by mcdallas** [comment]
From [wiki](https://en.bitcoin.it/wiki/Script)
> Compares the first signature against each public key until it finds an ECDSA match. Starting with the subsequent public key, it compares the second signature against each remaining public key until it finds an ECDSA match. The process is repeated until all signatures have been checked or not enough public keys remain to produce a successful result. All signatures need to match a public key. Because public keys are not checked again if they fail any signature comparison, signatures must be placed in the scriptSig using the same order as their corresponding public keys were placed in the scriptPubKey or redeemScript. If all signatures are valid, 1 is returned, 0 otherwise. Due to a bug, one extra unused value is removed from the stack.

**Comment by Anynomouss** [comment]
hi @mcdallas any chance you can push the fix some time soon? E.g. dropping keys if a valid signature is found.
We need this part of the code to work for our security proofs in order to receive funding from the Grin Original Council (OC).
