### ISSUE TITLE
Why  everytime create a transaction  , sent all balance amount ? 

### ISSUE THREAD

**Issue by lightlizm** [mcdallas/cryptotools#3]
import os
os.environ['CRYPTOTOOLS_NETWORK'] = 'test'

from btctools import PrivateKey, Address

private = PrivateKey.from_hex('mysupersecretkey')
address = Address('n2NGrooSecJaiD6ssp4YqFoj9eZ7GrCJ66')

>>> address.balance()
0.55

send_to = {'n4SbPWR6EmQMsWaQVYYFXiJgjweGKE4XnQ': 0.1, 'n2NGrooSecJaiD6ssp4YqFoj9eZ7GrCJ66': 0.4}

tx = address.send(to=send_to, fee=0.05, private=private)
>>> tx
Transaction(inputs=1, outputs=2)
---------------------------------------------------------------------------------------
Why  everytime create a transaction  , sent all balance amount ? 

If one unspent_outputs can pay enough, Actually, no need to add all unspent_outputs.
such as :https://www.blocktrail.com/tBTC/tx/b32cb7e657b8ba601dc081dbff144fa83e8ca5501cc22ce8b3aa21abf582bbd9

This way is not friendly ，even waste fee 

How can I fix it?

**Comment by mcdallas** [comment]
@lightlizm Coin selection is not implemented as it's a non-trivial problem and not really the focus of the project. Here is the relevant line that selects all unspent outputs by default if you want to tinker with it. https://github.com/mcdallas/cryptotools/blob/master/btctools/address.py#L147
