### ISSUE TITLE
BTC private keys to address and balance check

### ISSUE THREAD

**Issue by Handsomekaizer** [mcdallas/cryptotools#37]
I just stumbled on these your GitHub repo I was looking for a program that will help me convert my compressed Bitcoin private key to address and check the balance. Could you please help me update or create a python program that will help me convert my compressed private key to address and check the balance. The reason I needed this was to scan through a massive private key txt file and see if I can find my missing 6 characters private key. Please help me if I recover the wallet I will donate some BTC to you. Thanks

**Comment by Noname400** [comment]
НАдеюсь вы не ищите wif

**Comment by mcdallas** [comment]
This seems legit

![image](https://user-images.githubusercontent.com/15388116/173818253-1fa59607-8d55-40f7-b860-590659ce498e.png)
