### ISSUE TITLE
Need some advice. 

### ISSUE THREAD

**Issue by katineko** [mcdallas/cryptotools#40]
How do I get this to run or install? I have Python 3.12.

**Comment by mcdallas** [comment]
hi @katineko just type `pip install git+https://github.com/mcdallas/cryptotools.git` in the command line

**Comment by katineko** [comment]
> hi @katineko just type `pip install git+https://github.com/mcdallas/cryptotools.git` in the command line

Thank you for your reply. And I type this in Command Prompt, or Python?

**Comment by mcdallas** [comment]
in the command prompt

**Comment by michaelfolkson** [comment]
@mcdallas: Have you tried getting cryptotools on [PyPi](https://pypi.org/project/cryptotools/)? Might be worth a try. There's an email address for the current owner (esqaw at ytosi dot com)

**Comment by mcdallas** [comment]
@michaelfolkson I thought maybe it’s better to install it straight from git for transparency since there is no guarantee that the code on PyPi matches that on github

**Comment by katineko** [comment]
Will take a look, thank you : )

**Comment by katineko** [comment]
> hi @katineko just type `pip install git+https://github.com/mcdallas/cryptotools.git` in the command line

Oh, do I have to download anything on the github page? Like, go to file, for example? Or simply just type the command?

**Comment by katineko** [comment]
> 

Perhaps this will solve my issue?
https://www.alphr.com/pip-is-not-recognized-as-an-internal-or-external-command/#:~:text=Reinstall%20Python%20to%20Fix%20'Pip,components%20to%20fix%20the%20problem.

**Comment by michaelfolkson** [comment]
@katineko:

To check if Python3 is installed:

`python3 --version`

If it isn't install it here: https://www.python.org/downloads/

To check if pip3 is installed:

`pip3 --version`

If it isn't install it here: https://pip.pypa.io/en/stable/installation/
