### ISSUE TITLE
Is there an setup.py or pip install cyrptotools for this?

### ISSUE THREAD

**Issue by jamesyoungdigital** [mcdallas/cryptotools#5]
Thanks!

**Comment by mcdallas** [comment]
Not atm. It has no dependencies so cloning and putting it into your path should just work. Try to add this at the top of your script.

```
import sys
sys.path.append('path/to/cloned/project')
```

**Comment by captain-kark** [comment]
After some point though this repo ends up pulled in as a whole source tree, regardless if its the focus of the module or not. If you don't, relative imports between the modules won't work.

Is this something you'd be interested in merging upstream if I forked it and added it as a feature? My intention is to keep with the ultra-lightweight feel of the project and only expose a git-based pip install target via an extremely modest `setup.py` file in the root of the repo?

Awesome work on this project, by the way.

**Comment by mcdallas** [comment]
Hey @captain-kark, glad you found it useful!

> Is this something you'd be interested in merging upstream if I forked it and added it as a feature? My intention is to keep with the ultra-lightweight feel of the project and only expose a git-based pip install target via an extremely modest setup.py file in the root of the repo.

 Yes that sounds good, go for it

**Comment by captain-kark** [comment]
```
Ran 33 tests in 55.861s

OK
```

I'll post here with the PR after I confirm an install works.

**Comment by mcdallas** [comment]
You can now use pip to install this library thanks to @captain-kark 

DO NOT try pip install cryptotools because it is a different package, 
instead do `pip install git+https://github.com/mcdallas/cryptotools.git` 
as the README suggests
